import 'package:travelsphere/models/package_model.dart';
import 'package:latlong2/latlong.dart';

class MockDataService {
  static final List<TravelPackage> mockPackages = [
    // Existing 6 Packages
    TravelPackage(
      id: '1',
      name: 'Munnar Mist',
      imageUrl: 'https://images.unsplash.com/photo-1596329486780-87a1d7c3b9dd?auto=format&fit=crop&w=800&q=80',
      price: 5000,
      rating: 4.8,
      duration: '3 Days',
      location: 'Kerala',
      description: 'Experience the serene beauty of Munnar with its tea gardens, misty hills, and breathtaking waterfalls. Perfect for nature lovers.',
      itinerary: ['Day 1: Arrival and Tea Museum', 'Day 2: Eravikulam National Park', 'Day 3: Departure'],
      locationCoordinates: const LatLng(10.0889, 77.0595),
    ),
    TravelPackage(
      id: '2',
      name: 'Goa Beach Party',
      imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
      price: 8000,
      rating: 4.5,
      duration: '4 Days',
      location: 'Goa',
      description: 'Sun, sand, and parties! Enjoy the vibrant nightlife and relaxing beaches of Goa.',
      itinerary: ['Day 1: Arrival and Calangute Beach', 'Day 2: Water Sports', 'Day 3: South Goa Tour', 'Day 4: Departure'],
      locationCoordinates: const LatLng(15.2993, 74.1240),
    ),
    TravelPackage(
      id: '3',
      name: 'Wayanad Escape',
      imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
      price: 4500,
      rating: 4.7,
      duration: '2 Days',
      location: 'Kerala',
      description: 'A quick getaway to the lush green forests and caves of Wayanad.',
      itinerary: ['Day 1: Edakkal Caves', 'Day 2: Banasura Sagar Dam'],
      locationCoordinates: const LatLng(11.6854, 76.1320),
    ),
    TravelPackage(
      id: '4',
      name: 'Jaipur Royals',
      imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
      price: 12000,
      rating: 4.9,
      duration: '5 Days',
      location: 'Rajasthan',
      description: 'Walk through the pink city, visit majestic forts and experience royal hospitality.',
      itinerary: ['Day 1: Hawa Mahal', 'Day 2: Amber Fort', 'Day 3: City Palace', 'Day 4: Shopping', 'Day 5: Departure'],
      locationCoordinates: const LatLng(26.9124, 75.7873),
    ),
    TravelPackage(
      id: '5',
      name: 'Manali Snow Trek',
      imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
      price: 15000,
      rating: 4.6,
      duration: '6 Days',
      location: 'Himachal Pradesh',
      description: 'Adventure calls! Trek through snow-capped mountains and enjoy the chilly breeze.',
      itinerary: ['Day 1: Arrival', 'Day 2: Solang Valley', 'Day 3: Rohtang Pass', 'Day 4-5: Trekking', 'Day 6: Departure'],
      locationCoordinates: const LatLng(32.2432, 77.1892),
    ),
    TravelPackage(
      id: '6',
      name: 'Ooty Tea Gardens',
      imageUrl: 'https://images.unsplash.com/photo-1582239478431-7e874932aa9c?auto=format&fit=crop&w=800&q=80',
      price: 6000,
      rating: 4.4,
      duration: '3 Days',
      location: 'Tamil Nadu',
      description: 'Relax in the queen of hill stations with boat rides and homemade chocolates.',
      itinerary: ['Day 1: Botanical Garden', 'Day 2: Dodabetta Peak', 'Day 3: Pykara Lake'],
      locationCoordinates: const LatLng(11.4102, 76.6950),
    ),
    // 20 New Packages
    TravelPackage(
      id: '7',
      name: 'Taj Mahal Wonder',
      imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
      price: 7000,
      rating: 4.9,
      duration: '2 Days',
      location: 'Agra, UP',
      description: 'Witness the symbol of love, the Taj Mahal, in all its glory at sunrise.',
      itinerary: ['Day 1: Taj Mahal Tour', 'Day 2: Agra Fort & Shopping'],
      locationCoordinates: const LatLng(27.1751, 78.0421),
    ),
    TravelPackage(
      id: '8',
      name: 'Varanasi Spiritual',
      imageUrl: 'https://images.unsplash.com/photo-1561361513-35bdcd2570cc?auto=format&fit=crop&w=800&q=80',
      price: 5500,
      rating: 4.6,
      duration: '3 Days',
      location: 'Varanasi, UP',
      description: 'Experience the spiritual capital of India with Ganga Aarti and boat rides.',
      itinerary: ['Day 1: Ganga Aarti', 'Day 2: Kashi Vishwanath Temple', 'Day 3: Sarnath Tour'],
      locationCoordinates: const LatLng(25.3176, 82.9739),
    ),
    TravelPackage(
      id: '9',
      name: 'Udaipur Lakes',
      imageUrl: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80',
      price: 11000,
      rating: 4.8,
      duration: '4 Days',
      location: 'Udaipur, Rajasthan',
      description: 'The City of Lakes awaits with its majestic palaces and romantic boat rides.',
      itinerary: ['Day 1: City Palace', 'Day 2: Lake Pichola Boat Ride', 'Day 3: Monsoon Palace', 'Day 4: Departure'],
      locationCoordinates: const LatLng(24.5854, 73.7125),
    ),
    TravelPackage(
      id: '10',
      name: 'Leh Ladakh Bike Trip',
      imageUrl: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80',
      price: 25000,
      rating: 4.9,
      duration: '7 Days',
      location: 'Ladakh',
      description: 'The ultimate adventure riding through the highest passes in the world.',
      itinerary: ['Day 1: Acclimatization', 'Day 2: Magnetic Hill', 'Day 3: Nubra Valley', 'Day 4: Pangong Lake', 'Day 5-7: Return Journey'],
      locationCoordinates: const LatLng(34.1526, 77.5770),
    ),
    TravelPackage(
      id: '11',
      name: 'Andaman Scuba',
      imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80',
      price: 30000,
      rating: 4.8,
      duration: '6 Days',
      location: 'Andaman Islands',
      description: 'Dive into the crystal clear waters of Havelock and explore coral reefs.',
      itinerary: ['Day 1: Port Blair', 'Day 2: Havelock Ferry', 'Day 3: Scuba Diving', 'Day 4: Radhanagar Beach', 'Day 5: Neil Island', 'Day 6: Departure'],
      locationCoordinates: const LatLng(11.9761, 92.9876),
    ),
    TravelPackage(
      id: '12',
      name: 'Mysore Royal Tour',
      imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      price: 6500,
      rating: 4.5,
      duration: '3 Days',
      location: 'Mysore, Karnataka',
      description: 'Explore the grand Mysore Palace and the beautiful Brindavan Gardens.',
      itinerary: ['Day 1: Mysore Palace', 'Day 2: Chamundi Hills', 'Day 3: Brindavan Gardens'],
      locationCoordinates: const LatLng(12.2958, 76.6394),
    ),
    TravelPackage(
      id: '13',
      name: 'Hampi Ruins',
      imageUrl: 'https://images.unsplash.com/photo-1600100598079-4235687b2928?auto=format&fit=crop&w=800&q=80',
      price: 7500,
      rating: 4.7,
      duration: '3 Days',
      location: 'Hampi, Karnataka',
      description: 'Step back in time to the Vijayanagara Empire with these magnificent ruins.',
      itinerary: ['Day 1: Virupaksha Temple', 'Day 2: Vitthala Temple', 'Day 3: Coracle Ride'],
      locationCoordinates: const LatLng(15.3350, 76.4600),
    ),
    TravelPackage(
      id: '14',
      name: 'Darjeeling Joyride',
      imageUrl: 'https://images.unsplash.com/photo-1544634076-a9016021f9fc?auto=format&fit=crop&w=800&q=80',
      price: 9000,
      rating: 4.6,
      duration: '4 Days',
      location: 'West Bengal',
      description: 'Ride the toy train and watch the sunrise over Kanchenjunga.',
      itinerary: ['Day 1: Tiger Hill Sunrise', 'Day 2: Toy Train Ride', 'Day 3: Tea Gardens', 'Day 4: Departure'],
      locationCoordinates: const LatLng(27.0410, 88.2663),
    ),
    TravelPackage(
      id: '15',
      name: 'Rishikesh Rafting',
      imageUrl: 'https://images.unsplash.com/photo-1589802829985-d3a54d485c2c?auto=format&fit=crop&w=800&q=80',
      price: 5000,
      rating: 4.8,
      duration: '3 Days',
      location: 'Uttarakhand',
      description: 'Adrenaline pumping river rafting and peaceful yoga by the Ganges.',
      itinerary: ['Day 1: Arrival & Camping', 'Day 2: River Rafting', 'Day 3: Beatles Ashram'],
      locationCoordinates: const LatLng(30.0869, 78.2676),
    ),
    TravelPackage(
      id: '16',
      name: 'Golden Amritsar',
      imageUrl: 'https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=800&q=80',
      price: 4000,
      rating: 4.9,
      duration: '2 Days',
      location: 'Punjab',
      description: 'Find inner peace at the Golden Temple and witness the Wagah Border ceremony.',
      itinerary: ['Day 1: Golden Temple', 'Day 2: Wagah Border'],
      locationCoordinates: const LatLng(31.6200, 74.8765),
    ),
    TravelPackage(
      id: '17',
      name: 'Jaisalmer Desert Safari',
      imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80',
      price: 13000,
      rating: 4.7,
      duration: '4 Days',
      location: 'Rajasthan',
      description: 'Camp under the stars in the Thar Desert with camel safaris and folk dance.',
      itinerary: ['Day 1: Jaisalmer Fort', 'Day 2: Sam Sand Dunes', 'Day 3: Camel Safari', 'Day 4: Departure'],
      locationCoordinates: const LatLng(26.9157, 70.9083),
    ),
    TravelPackage(
      id: '18',
      name: 'Kodaikanal Bliss',
      imageUrl: 'https://images.unsplash.com/photo-1549144511-30852b39233e?auto=format&fit=crop&w=800&q=80',
      price: 6000,
      rating: 4.5,
      duration: '3 Days',
      location: 'Tamil Nadu',
      description: 'The Princess of Hill Stations. Enjoy boating and misty pine forests.',
      itinerary: ['Day 1: Kodai Lake', 'Day 2: Coakers Walk', 'Day 3: Pillar Rocks'],
      locationCoordinates: const LatLng(10.2381, 77.4892),
    ),
    TravelPackage(
      id: '19',
      name: 'Coorg Coffee Trail',
      imageUrl: 'https://images.unsplash.com/photo-1590766940554-634a7ed41450?auto=format&fit=crop&w=800&q=80',
      price: 7000,
      rating: 4.6,
      duration: '3 Days',
      location: 'Karnataka',
      description: 'Wake up to the aroma of fresh coffee in the Scotland of India.',
      itinerary: ['Day 1: Abbey Falls', 'Day 2: Dubare Elephant Camp', 'Day 3: Coffee Plantation Tour'],
      locationCoordinates: const LatLng(12.3375, 75.8069),
    ),
    TravelPackage(
      id: '20',
      name: 'Alleppey Houseboat',
      imageUrl: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      price: 10000,
      rating: 4.8,
      duration: '2 Days',
      location: 'Kerala',
      description: 'Cruise through the backwaters in a traditional houseboat.',
      itinerary: ['Day 1: Check-in Houseboat', 'Day 2: Sunrise Cruise & Departure'],
      locationCoordinates: const LatLng(9.4981, 76.3388),
    ),
    TravelPackage(
      id: '21',
      name: 'Gangtok Peaks',
      imageUrl: 'https://images.unsplash.com/photo-1588414734732-660b07304ddb?auto=format&fit=crop&w=800&q=80',
      price: 14000,
      rating: 4.7,
      duration: '5 Days',
      location: 'Sikkim',
      description: 'Experience the pristine beauty of the Himalayas and Buddhist monasteries.',
      itinerary: ['Day 1: MG Marg', 'Day 2: Tsomgo Lake', 'Day 3: Nathula Pass', 'Day 4: Rumtek Monastery', 'Day 5: Departure'],
      locationCoordinates: const LatLng(27.3314, 88.6138),
    ),
    TravelPackage(
      id: '22',
      name: 'Shillong Clouds',
      imageUrl: 'https://images.unsplash.com/photo-1582650625119-3a31f8fa2699?auto=format&fit=crop&w=800&q=80',
      price: 12500,
      rating: 4.6,
      duration: '4 Days',
      location: 'Meghalaya',
      description: 'Visit the abode of clouds, living root bridges, and deepest caves.',
      itinerary: ['Day 1: Umiam Lake', 'Day 2: Cherrapunji', 'Day 3: Living Root Bridge', 'Day 4: Dawki River'],
      locationCoordinates: const LatLng(25.5788, 91.8933),
    ),
    TravelPackage(
      id: '23',
      name: 'Pondicherry French',
      imageUrl: 'https://images.unsplash.com/photo-1582915293078-836eed323250?auto=format&fit=crop&w=800&q=80',
      price: 5500,
      rating: 4.5,
      duration: '3 Days',
      location: 'Pondicherry',
      description: 'A touch of France in India. Beautiful promenade, cafes, and Auroville.',
      itinerary: ['Day 1: Promenade Beach', 'Day 2: Auroville', 'Day 3: French Colony Walk'],
      locationCoordinates: const LatLng(11.9416, 79.8083),
    ),
    TravelPackage(
      id: '24',
      name: 'Mahabalipuram Arts',
      imageUrl: 'https://images.unsplash.com/photo-1597825700755-12e379430c51?auto=format&fit=crop&w=800&q=80',
      price: 4000,
      rating: 4.4,
      duration: '2 Days',
      location: 'Tamil Nadu',
      description: 'UNESCO World Heritage site famous for its shore temples and rock carvings.',
      itinerary: ['Day 1: Shore Temple', 'Day 2: Pancha Rathas'],
      locationCoordinates: const LatLng(12.6208, 80.1945),
    ),
    TravelPackage(
      id: '25',
      name: 'Khajuraho Temples',
      imageUrl: 'https://images.unsplash.com/photo-1598501168545-2f88325997b1?auto=format&fit=crop&w=800&q=80',
      price: 6000,
      rating: 4.6,
      duration: '2 Days',
      location: 'Madhya Pradesh',
      description: 'Famous for its stunning intricate sculptures and ancient temples.',
      itinerary: ['Day 1: Western Group of Temples', 'Day 2: Eastern Group of Temples'],
      locationCoordinates: const LatLng(24.8318, 79.9199),
    ),
    TravelPackage(
      id: '26',
      name: 'Kashmir Paradise',
      imageUrl: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80',
      price: 22000,
      rating: 4.9,
      duration: '6 Days',
      location: 'J&K',
      description: 'Paradise on Earth. Dal Lake shikara rides and snow in Gulmarg.',
      itinerary: ['Day 1: Dal Lake', 'Day 2: Gulmarg Gondola', 'Day 3: Pahalgam', 'Day 4: Sonamarg', 'Day 5: Shopping', 'Day 6: Departure'],
      locationCoordinates: const LatLng(34.0837, 74.7973),
    ),
  ];
}
