import '../models/package_model.dart';

class MockDataService {
  static final List<TravelPackage> mockPackages = [
    TravelPackage(
      id: '1',
      name: 'andi puri',
      imageUrl: 'https://images.unsplash.com/photo-1596329486780-87a1d7c3b9dd?auto=format&fit=crop&w=800&q=80',
      price: 5000,
      rating: 4.8,
      duration: '3 Days',
      location: 'Kerala',
      description: 'Experience the serene beauty of Munnar with its tea gardens, misty hills, and breathtaking waterfalls. Perfect for nature lovers.',
      itinerary: ['Day 1: Arrival and Tea Museum', 'Day 2: Eravikulam National Park', 'Day 3: Departure'],
    ),
    TravelPackage(
      id: '2',
      name: 'Goa Beach Party',
      imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2', // Removed query params for cleaner URLs in mock
      price: 8000,
      rating: 4.5,
      duration: '4 Days',
      location: 'Goa',
      description: 'Sun, sand, and parties! Enjoy the vibrant nightlife and relaxing beaches of Goa.',
      itinerary: ['Day 1: Arrival and Calangute Beach', 'Day 2: Water Sports', 'Day 3: South Goa Tour', 'Day 4: Departure'],
    ),
    TravelPackage(
      id: '3',
      name: 'Wayanad Escape',
      imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1',
      price: 4500,
      rating: 4.7,
      duration: '2 Days',
      location: 'Kerala',
      description: 'A quick getaway to the lush green forests and caves of Wayanad.',
      itinerary: ['Day 1: Edakkal Caves', 'Day 2: Banasura Sagar Dam'],
    ),
    TravelPackage(
      id: '4',
      name: 'Jaipur Royals',
      imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245',
      price: 12000,
      rating: 4.9,
      duration: '5 Days',
      location: 'Rajasthan',
      description: 'Walk through the pink city, visit majestic forts and experience royal hospitality.',
      itinerary: ['Day 1: Hawa Mahal', 'Day 2: Amber Fort', 'Day 3: City Palace', 'Day 4: Shopping', 'Day 5: Departure'],
    ),
    TravelPackage(
      id: '5',
      name: 'Manali Snow Trek',
      imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23',
      price: 15000,
      rating: 4.6,
      duration: '6 Days',
      location: 'Himachal Pradesh',
      description: 'Adventure calls! Trek through snow-capped mountains and enjoy the chilly breeze.',
      itinerary: ['Day 1: Arrival', 'Day 2: Solang Valley', 'Day 3: Rohtang Pass', 'Day 4-5: Trekking', 'Day 6: Departure'],
    ),
    TravelPackage(
      id: '6',
      name: 'Ooty Tea Gardens',
      imageUrl: 'https://images.unsplash.com/photo-1582239478431-7e874932aa9c',
      price: 6000,
      rating: 4.4,
      duration: '3 Days',
      location: 'Tamil Nadu',
      description: 'Relax in the queen of hill stations with boat rides and homemade chocolates.',
      itinerary: ['Day 1: Botanical Garden', 'Day 2: Dodabetta Peak', 'Day 3: Pykara Lake'],
    ),
  ];
}
